sudo: false
services:
  - docker
before_install:
  - docker pull gcc:latest
  - docker pull rsmmr/clang:latest
env:
  matrix:
    - CC=gcc
    - CC=clang
script:
  - if [ "$CC" == "gcc" ]; then
      docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp gcc /bin/sh -c "$CC -v && make test";
    else
      docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp rsmmr/clang /bin/sh -c "$CC -v && make test";
    fi
