language: generic
sudo: false
services:
  - docker
matrix:
  include:
    - env:
      - CXX=g++
        DOC=dousu/ubuntu_gcc8_dev
      install:
        - docker pull dousu/ubuntu_gcc8_dev
    - env:
      - CXX=clang++
        DOC=dousu/ubuntu_clang6_dev
      install:
        - docker pull dousu/ubuntu_clang6_dev
script:
  - docker run -t $DOC -e CXX /bin/sh -c "$CXX -v && make -j test"
notifications:
  email:
    on_failure: change
    on_success: never
