language: generic
sudo: false
services:
  - docker
matrix:
  include:
    - env:
      - CXX=g++
      install:
        - docker pull dousu/ubuntu_gcc8_dev
      script:
        - docker run -e CXX dousu/ubuntu_gcc8_dev -c "$CXX -v && make -j test"
    - env:
      - CXX=clang++
      install:
        - docker pull dousu/ubuntu_clang6_dev
      script:
        - docker run -e CXX dousu/ubuntu_clang6_dev -c "$CXX -v && make -j test"
notifications:
  email:
    on_failure: change
    on_success: never
