sudo: false
services:
  - docker
env:
  matrix:
    - DOCKERIMAGE="gcc" CXX="g++"
    - DOCKERIMAGE="rsmmr/clang" CXX="clang++ -stdlib=libc++"
install:
  - docker pull $DOCKERIMAGE
script:
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -e CXX $DOCKERIMAGE /bin/sh -c "$CXX -v && make test"
