language: generic
sudo: false
env:
  matrix:
    - CXX=g++
install:
  - docker pull dousu/msilm
script:
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -e CXX dousu/msilm /bin/sh -c "$CXX -v && make -j test"
notifications:
  email:
    on_failure: change
