language: cpp
sudo: false
env:
  matrix:
    - DOCKERIMAGE="gcc" CXX="g++"
      compiler: gcc
    - DOCKERIMAGE="rsmmr/clang" CXX="clang++ -stdlib=libc++"
      compiler: clang
install:
  - docker pull $DOCKERIMAGE
script:
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -e CXX $DOCKERIMAGE /bin/sh -c "$CXX -v && make -j test"
notifications:
  email:
    on_failure: change