language: generic
sudo: false
services:
  - docker
matrix:
  include:
    - env:
      - CXX=g++
        DOC=dousu/ubuntu_gcc8_dev
      install:
        - docker pull $DOC
    - env:
      - CXX=clang++
        DOC=dousu/ubuntu_clang6_dev
      install:
        - docker pull $DOC
script:
  - docker run -e CXX $DOC /bin/sh -c "$CXX -v && make -j test"
notifications:
  email:
    on_failure: change
    on_success: never
