language: cpp
install: sudo apt-get install -y libboost-all-dev
script: make test
dist: trusty
sudo: required
os: linux
branches:
  only:
    - master
    - readability
    - ex_boost
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get install -y clang-6.0 clang++-6.0
notifications:
  email:
    on_failure: change