language: cpp
sudo: false
services:
  - docker
env:
  matrix:
    - DOCKERIMAGE="gcc" CXX="g++"
    - DOCKERIMAGE="rsmmr/clang" MATRIX_EVAL="CXX=\"clang++-6.0\""
install:
  - docker pull $DOCKERIMAGE
  - eval "${MATRIX_EVAL}"
script:
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp -e CXX $DOCKERIMAGE /bin/sh -c "$CXX -v && make test"
