language: cpp
sudo: false
services:
  - docker
before_install:
  - docker pull asciian/docker-boost-gcc
script:
  - docker run --rm -v $PWD:/usr/src/myapp -w /usr/src/myapp asciian/docker-boost-gcc make test
